language: objective-c  #1
osx_image: xcode8 #2
xcode_project: MidtransSDK.xcworkspace #3
branches:
  only:
    - development
before_install:
  # Until Travis upgrades from Cocoapods 0.39, we need to do it here.
  - pod --version
  - gem uninstall cocoapods -a
  - gem install cocoapods -v '1.0.1'
  - pod --version
  # Recent pods aren't found if we don't explicitly update Cocoapods' repo.
  - pod repo update
  - brew install gflags
install:
  - pod install
  - pod update
notifications:
  email: true
  slack: midtrans:0RQSD3O4kPhQy9KxlPZsFYXp
